name: Just a Test
pool:
  vmImage: 'VS2017-Win2016'
steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: SecretConfig.Azure.ps1
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: 'Get-Item Env:'
  - task: PowerShell@2
    name: SecondTask
    inputs:
      targetType: inline
      script: 'cd C:\Program Files\IIS && ls'
  - script: echo Hello $(Agent.TempDirectory) , world!
    displayName: 'Run a one-line script'
  - powershell: cd $env:AGENT_TEMPDIRECTORY && ls
