variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: 'VS2017-Win2016'

steps:

- task: DownloadSecureFile@1
  inputs:
    secureFile: SecretConfig.Azure.ps1

- powershell: iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  displayName: Install Chocolatey

- script: cinst psake
  displayName: Install psake

- powershell: psake azure-checkout
  displayName: Git Checkout

- script: psake package-web
  displayName: Package (Development)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  env:
    Environment: Development
    SecretConfigPath: '$(Agent.TempDirectory)\SecretConfig.Azure.ps1'

- script: psake package-web
  displayName: Package (Staging)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
  env:
    Environment: Staging
    SecretConfigPath: '$(Agent.TempDirectory)\SecretConfig.Azure.ps1'

- script: psake package-web
  displayName: Package (Production)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  env:
    Environment: Production
    SecretConfigPath: '$(Agent.TempDirectory)\SecretConfig.Azure.ps1'

- task: PublishPipelineArtifact@0
  displayName: Publish Artifact (Development)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    artifactName: 'WebDevelopment'
    targetPath: out

- task: PublishPipelineArtifact@0
  displayName: Publish Artifact (Staging)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
  inputs:
    artifactName: 'WebStaging'
    targetPath: out

- task: PublishPipelineArtifact@0
  displayName: Publish Artifact (Production)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  inputs:
    artifactName: 'WebProduction'
    targetPath: out

- script: echo "##vso[build.addbuildtag]ProductionRelease" 
  displayName: Add Build Tag
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
