name: Just a Test
pool:
  vmImage: 'VS2017-Win2016'
steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: 'Get-Item Env:'
  - task: PowerShell@2
    name: SecondTask
    inputs:
      script: 'cd C:\Program Files\IIS && ls'
  - script: echo Hello, world!
    displayName: 'Run a one-line script'