steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: 'ls env:'
  - task: PowerShell@2
    name: SecondTask
    inputs:
      script: 'cd C:\Program Files\IIS && ls'
  - script: echo Hello, world!
    displayName: 'Run a one-line script'