variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: 'VS2017-Win2016'

steps:
- powershell: git checkout -B $env:BUILD_SOURCEBRANCHNAME $env:BUILD_SOURCEVERSION
  displayName: Git Checkout
- task: DownloadSecureFile@1
  inputs:
    secureFile: SecretConfig.Azure.ps1
- powershell: iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  displayName: Install Chocolatey
- script: cinst psake
  displayName: Install psake

- powershell: 'Get-Item Env:'

- script: psake package-web
  displayName: Package (Development)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  env:
    Environment: Development
    SecretConfigPath: '$(Agent.TempDirectory)\SecretConfig.Azure.ps1'

- script: psake package-web
  displayName: Package (Staging)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
  env:
    Environment: Staging
    SecretConfigPath: '$(Agent.TempDirectory)\SecretConfig.Azure.ps1'

- script: psake package-web
  displayName: Package (Production)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  env:
    Environment: Production
    SecretConfigPath: '$(Agent.TempDirectory)\SecretConfig.Azure.ps1'

- task: PublishPipelineArtifact@0
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
  inputs:
    artifactName: 'artifactName'
    targetPath: out
